import unreal

from toolset_registry.agent_skill import agent_skill


_INSTRUCTIONS = (
    "Before changing a VRM4U material, inspect the source VRM metadata, VRM "
    "version, material type recorded at import, skeletal-mesh material "
    "assignments, and the parents of the generated material instances. Treat "
    "the recorded import type as historical metadata and determine each "
    "material's effective type from its current parent. Changing a parent does "
    "not update the recorded import type and may be overwritten by reimport or "
    "material regeneration.\n"
    "The material type can be selected during import. To change it afterward, "
    "change each generated material instance's parent to the corresponding "
    "VRM4U base material for the desired type. Before changing a parent, "
    "preserve intentional instance overrides and "
    "confirm that the new parent exposes compatible parameters; afterward, "
    "verify the skeletal-mesh material assignments.\n"
    "Primarily choose among MToon Unlit, MToon Lit, and Subsurface Profile. "
    "For an initial comparison, recommend trying VRMIMT_MToonUnlit first, then "
    "VRMIMT_SSSProfile. Use VRMIMT_MToonUnlit when the material should not be "
    "affected by scene lighting, MToon Lit when it should receive a limited "
    "amount of lighting influence, and recommend VRMIMT_SSSProfile when the "
    "character should be combined with or blend into Unreal Engine's "
    "PBR-rendered surfaces.\n"
    "The importer initially creates and assigns one skin-oriented Subsurface "
    "Profile to the generated materials. For non-skin parts, duplicate that "
    "generated profile, reduce the saturation of the duplicate's scattering-"
    "color settings, and assign only the duplicate to the corresponding non-"
    "skin material instances. Leave the original profile assigned to skin.\n"
    "Do not assume that parameter names are identical across material types or "
    "VRM4U versions. Inspect the currently assigned material instance and its "
    "parent, then change only parameters exposed by that material path.\n"
    "Tune the material in dependency order: establish base color and textures; "
    "fix opacity mode, cutoff, culling, and two-sided behavior; shape the shade "
    "and lighting response; then tune emission, rim, and outline. This keeps "
    "render-path problems from being mistaken for artistic parameter problems.\n"
    "If surfaces have an incorrect front-to-back relationship, use the ZOffset "
    "parameter to apply a depth offset, then verify the result from the intended "
    "camera angles.\n"
    "For color matching, adjust TexturePow first. If TexturePow alone cannot "
    "produce the intended color, use mtoon_Color for the remaining correction.\n"
    "Use the MRSA parameter to tune the material's surface quality through its "
    "Metallic, Roughness, and Specular values. Judge these values together under "
    "the intended lighting rather than tuning each one in isolation.\n"
    "For eyes, eyebrows, eyelashes, sclera (eye whites), mouth interiors, and "
    "tongues, set Roughness to 1 and Specular to 0. Apply this rule to every "
    "material representing those parts, including separate iris, highlight, "
    "eyeline, mouth, or tongue material slots.\n"
    "For clothing, first create visible differences in Roughness between its "
    "material regions. Then apply stronger Metallic values to the parts that "
    "should read as metal, keeping Metallic roughly within 0.1 to 0.9.\n"
    "When the current material path exposes bUseCustomAniso, enable it to render "
    "a simulated anisotropic reflection. Use it after the base MRSA adjustment "
    "when a richer appearance is desired, then verify the highlights under the "
    "intended lighting and camera.\n"
    "To make emissive colors blend more naturally with PBR-rendered surfaces, "
    "enable bEmissiveAsBaseColor to add the emissive contribution to Base Color. "
    "Recheck the result under the intended lighting and exposure.\n"
    "For facial materials, use the normal-correction controls as the starting "
    "point for appearance tuning. Start with NormalFresnelScale set to 2 and "
    "NormalToCameraMat set to 1, then adjust the correction strength while "
    "checking the face from the intended camera angles and under the intended "
    "lighting.\n"
    "On a compatible opaque parent that exposes it, enable bUseDitherAlpha when "
    "partial transparency should be represented with a dithered alpha effect. "
    "This path uses DitherTemporalAA, so verify it with the project's actual "
    "anti-aliasing mode at the intended viewing distance and camera angle. Do "
    "not assume that translucent or other incompatible parents expose it.\n"
    "Before using ScreenBlend, set Project Settings > Rendering > Custom Depth-"
    "Stencil Pass to Enabled with Stencil and ensure the intended meshes write "
    "the expected custom-stencil values.\n"
    "ScreenBlend is available in VRM4U's basic materials and allows partial "
    "transparency by using render targets from a VrmSceneCaptureComponent2D. "
    "Both sides require configuration: assign the base-color, depth, and custom-"
    "stencil render targets to the scene-capture component, then assign those "
    "same textures to the corresponding screen-texture inputs in the material "
    "before enabling ScreenBlend. Confirm that the capture targets are updating "
    "and the material inputs reference them before diagnosing opacity settings.\n"
    "Treat the per-material MToon rim and VRM4U's screen-space rim-light filter "
    "as separate effects that may be layered. Keep the material rim as the "
    "always-on surface-local character shading, and add the screen-space filter "
    "for special moments or stencil-selected image-space emphasis. When both "
    "are active, judge and tune the combined result.\n"
    "Validate skin, hair, eyes, and translucent materials under the intended "
    "lighting and camera. Check outlines at both near and far distances, and "
    "verify that expression-driven material changes still work before saving.\n"
)


@agent_skill
class VRM4UMaterialSkill(unreal.AgentSkill):
    """Use when selecting or changing VRM4U material types or tuning generated
    MToon materials, including shading, ScreenBlend transparency, rim, outline,
    and emission."""

    instructions = _INSTRUCTIONS
